permissions = {'/get_plans': 'Команда /get_plans',
               '/restart': 'Команда /restart',
               '/emails': 'Команда /emails',
               '/get_user': 'Команда /get_user',
               '/get_logs': 'Команда /get_logs',
               '/notify': 'Команда /notify',
               '/get_users': 'Команда /get_users (В разработке)',
               '/get_banned_users': 'Команда /get_banned_users (В разработке)',
               '/get_admins': 'Команда /get_admins (В разработке)',
               '/edit_regions': 'Команда /edit_regions (В разработке)',
               '/edit_sections': 'Команда /edit_sections (В разработке)',
               'tech_supporter': 'Теx. поддержка (В разработке)',
               'edit_users': 'Редактировать пользователей',
               'edit_users_fullname': 'Изменять ФИО пользователей',
               'edit_users_location': 'Изменять регион пользователей',
               'edit_users_section': 'Изменять отдел пользователей',
               'edit_users_notifications': 'Управлять оповещениями пользователей, давать права управлять этим пунктом пользователям',
               'invite_new_users': 'Приглашать новых сотрудников',
               '/ban': 'Блокировка пользователей',
               '/kick': 'Удаление пользователей',
               '/unban': 'Команда /unban, разблокировка пользователей',
               '/edit_catalog': 'Команда /edit_catalog, изменение каталога',
               '/check_phone': 'Команда /check_phone, пробив номера',
               'responder': 'Команда /requests, возможность управлять запросами на доступ',
               'choose_admins': 'Выбирать администраторов'}
